### ISSUE TITLE
Examples fail on C64?

### ISSUE THREAD

**Issue by ssuukk** [AriZuu/picoos#1]
Hello,

Any hints on building picoos examples for C64? I tried them all and they seem to freeze the machine. What I did was:

1) remove OPT_LD_FIRST entry from 6502 .mak, as c64.o is supposedly no longer needed.

2) compile examples with: make PORT=6502 BUILD=RELEASE

They compile OK, they load OK, there's a standard BASIC stub with SYS xxxx, and when run C64 just changes to lowercase/uppercase mode and... nothing! I've checked my cc65 environment and it compiles working code (when not using picoos)!

P.S. I was hoping to port TinyGC (https://github.com/ivmai/tinygc) to picoos, do you think it's even possible?

**Comment by AriZuu** [comment]
Sorry, I cannot help much with C64 port. I used to have Sinclair stuff so it was Z80 for me, not 6502 :-)
There seems to be nano layer console support in arch_a.s, so I guess that there should be some output
from tests. There seems to be a makefile in ports/6502/test, maybe you could try to use it for 
compiling.

Is the c64.o unnecessary because of current compiler version ? From quick googling it seems to have
contained startup code.

About TinyGC: Don't know if it would be possible to get it up and running, but if you do, it is easy
to hook it up with pico]OS by using NOSCFG_MEM_MANAGER_TYPE 2, which allows user to supply memory allocation routines. But TinyGC seems to contain a lot of code (more than 3900 lines), pico]OS n_mem (malloc-style stuff) is only abou 550 lines, so there is a big difference in complexity. 

I don't know how well GC suits into idea of realtime system, but it might be interesting to see.

TinyGC license seems incompatible with pico]OS license (GPL vs BSD), but there seems to be an exception in license which allows one to build executable with it.

**Comment by ssuukk** [comment]
About c64.o I just found this:
http://retrohackers.com/viewtopic.php?f=4&t=534
22.05.2016 8:41 PM "Ari Suutari" <notifications@github.com> napisał(a):

**Comment by AriZuu** [comment]
Do you think you could try to debug the system to find out how far it gets ? It should at least reach main because there is not pico]OS stuff before that. After that, interesting points are p_pos_initArch and the start of function that should be executed by main thread.

Is there a good emulator that could be used to test the system instead of real hardware ?

**Comment by ssuukk** [comment]
I'll try that.

Sure there's an emulator. Try vice, it has monitor and a freezer. You can
launch compiled c64 binary by just: x64 filename
22.05.2016 9:09 PM "Ari Suutari" <notifications@github.com> napisał(a):

**Comment by AriZuu** [comment]
I just installed cc65 to my development box. I was able to compile with the change suggested by you,
I'll try to run it with vice :-)

**Comment by AriZuu** [comment]
![screen shot 2016-05-22 at 22 23 23](https://cloud.githubusercontent.com/assets/5243156/15455994/ec33c812-206b-11e6-9144-131005e0e5f9.png)

This is screenshot from vice which has been started with "x64 test.c64". I compiled it with the makefile in picoos/ports/6502/test.

So it works :-)

**Comment by AriZuu** [comment]
I just committed your change into 6502/port.mak.

**Comment by ssuukk** [comment]
Great, I'll test it in a few hours! Thanks for trying that. Have you tried
other demos?
22.05.2016 9:28 PM "Ari Suutari" <notifications@github.com> napisał(a):

**Comment by ssuukk** [comment]
Ok, tested it now. Same result... Maybe I have to recreate my build
environment... At least I know it should work and it does work somewhere. :D
22.05.2016 9:50 PM "Grdykopląs Namorzyn" <ssuukk2@gmail.com> napisał(a):

**Comment by AriZuu** [comment]
I didn't try other demos (yet).

**Comment by ssuukk** [comment]
Correction - the example from port dir runs printing copytight message (blinks for an fraction of second) and crashes. OK, won't bother you anymore, I'll just recreate my build environment. What cc65 version did you use?

**Comment by AriZuu** [comment]
I used V2.13.3 (the one available from FreeBSD ports). The makefile under test doesn't specify BUILD so it uses DEBUG. You used RELEASE in you first test, could this cause the difference ?

**Comment by AriZuu** [comment]
I tried other examples too, they seem to work with my compiler & vice version.
However, I find the examples directory a little bit confusing, because it contains both
examples you can compile and some configuration file examples (like poscfg.h & noscfg.h) which are not related to compilable applications. I'll reorganize that a little bit.

**Comment by ssuukk** [comment]
thanks, I still wonder what's wrong with my build environment...
23.05.2016 4:23 PM "Ari Suutari" <notifications@github.com> napisał(a):

**Comment by ssuukk** [comment]
Looking at this output, can you see anything that might be wrong with my build?:

qus@VUbuntu:~/Devel/picoos/ports/6502/test$ make all
../../../make/common.mak:130: Build mode not specified. Now using BUILD=DEBUG
../../../ports/6502/port.mak:51: CC65_HOME variable not set. Make may fail compiling the sources
make -C ../../../ --no-print-directory all OLIBNAME=picoos
ports/6502/port.mak:51: CC65_HOME variable not set. Make may fail compiling the sources
cc65 -g -t c64 -O -T -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/src/pico/picoos.i -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK src/pico/picoos.c
ca65 -t c64 -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/src/pico/picoos.o -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/src/pico/picoos.i
rm -f /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/src/pico/picoos.i
cc65 -g -t c64 -O -T -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/ports/6502/arch_c.i -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK ports/6502/arch_c.c
ca65 -t c64 -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/ports/6502/arch_c.o -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/ports/6502/arch_c.i
rm -f /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/ports/6502/arch_c.i
ca65 -t c64 -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/ports/6502/arch_a.o -I. -Iinc -Iports/6502/default -Iports/6502 -D_DBG -D_POSPACK ports/6502/arch_a.s
ar65 a /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/lib/picoos.lib /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/src/pico/picoos.o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/ports/6502/arch_c.o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/picoos/ports/6502/arch_a.o 
cc65 -g -t c64 -O -T -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/test/../../../examples/test.i -I. -I../../../inc -I../../../ports/6502/default -I../../../ports/6502 -D_DBG -D_POSPACK ../../../examples/test.c
ca65 -t c64 -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/test/../../../examples/test.o -I. -I../../../inc -I../../../ports/6502/default -I../../../ports/6502 -D_DBG -D_POSPACK /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/test/../../../examples/test.i
rm -f /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/test/../../../examples/test.i
ld65 -t c64 -Ln /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/out/test.lbl -m /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/out/test.map -o /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/out/test.c64  /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/obj/test/../../../examples/test.o  /home/qus/Devel/picoos/ports/6502/test/bin/6502-deb/lib/picoos.lib c64.lib

**Comment by AriZuu** [comment]
Compilation looks very much the same as for me.
[examples.zip](https://github.com/AriZuu/picoos/files/277919/examples.zip)

Here is a zip that contains test.c64 and ex_task3.c64, which work for me.
If they work for you also, then there is something wrong with compilation.

**Comment by ssuukk** [comment]
My test.c64 has even different size... Hmmm... The only thing I know for sure is we have different cc65.

**Comment by ssuukk** [comment]
Could you maybe see if it compiles with latest cc65? Maybe it's their bug? I'm using cc65 V2.15 - Git b0e9294

**Comment by AriZuu** [comment]
I tried that compiler version. Compiles, but doesn't work, symptoms look similar to yours.

**Comment by ssuukk** [comment]
Aha! Many thanks for trying!
23.05.2016 8:37 PM "Ari Suutari" <notifications@github.com> napisał(a):

**Comment by ssuukk** [comment]
Ok, so I can confirm picoos works with cc65 13. They must've changed
startup code or something...
23.05.2016 10:01 PM "Grdykopląs Namorzyn" <ssuukk2@gmail.com> napisał(a):

**Comment by AriZuu** [comment]
I did binary search of cc65 versions to find the point where it breaks. It seems
that cc65 compiled from 2015-05-23 sources produces working pico]OS but
from day later 2015-05-24 it no longer works.

**Comment by AriZuu** [comment]
In https://github.com/cc65/cc65.git, it looks like commit c30d87f0b7938ff3887dac2417324359b3fe8e12 is the last one that produces working compiler. I don't know if there is a bug in compiler, maybe something should be done differently in source code of pico]OS.

**Comment by ssuukk** [comment]
Interesting. I filed an issue with cc65, maybe that would help them?
24.05.2016 21:31 "Ari Suutari" <notifications@github.com> napisał(a):

**Comment by AriZuu** [comment]
Maybe. Certainly it would be worth mentioning to them.

**Comment by ssuukk** [comment]
My gut feeling is they might have changed something in zero page of 6502,
which can interfere with picoos multitasking, which also heavily depends on
zero page area. Note how picoos copyright message pops up before the app
crashes, probably when first task is started!
24.05.2016 21:48 "Ari Suutari" <notifications@github.com> napisał(a):

**Comment by AriZuu** [comment]
This should be kind of fixed in commit 0472621ca95eff38bc97a08e1233315a8d497bfa, which adds "--all-cdecl" switch to compiler to force usage of cdecl instead of fastcall. Eventually, the real fix will be making the initial task stack setup compatible with fastcall calling convention (I can write code in many assembly languages, but unfortunately 6502 assember is not one of them - so this will take some time).

**Comment by ssuukk** [comment]
I've written 6502 last time about 30 years ago, but if you explain what
should I do, maybe I could write it?

On Wed, May 25, 2016 at 6:34 PM, Ari Suutari <notifications@github.com>
wrote:

> This should be kind of fixed in commit 0472621
> <https://github.com/AriZuu/picoos/commit/0472621ca95eff38bc97a08e1233315a8d497bfa>,
> which adds "--all-cdecl" switch to compiler to force usage of cdecl instead
> of fastcall. Eventually, the real fix will be making the initial task stack
> setup compatible with fastcall calling convention (I can write code in many
> assembly languages, but unfortunately 6502 assember is not one of them - so
> this will take some time).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AriZuu/picoos/issues/1#issuecomment-221628410>
>



-- 

*XenoAmp* - a media player with a difference • Demo on [image: YouTube]
YouTube <http://www.youtube.com/watch?v=9O0xvDLw8Ek> • Get it ftom Google
Play <https://play.google.com/store/apps/details?id=pl.qus.xenoamp> • Folow
it on Twitter <https://twitter.com/XenoAmpMusic> • Report bugs to XDA Thread
<http://forum.xda-developers.com/showthread.php?t=1822492>

[image: XenoBanner]

**Comment by AriZuu** [comment]
This is now properly fixed with #2
